spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411

  cloud:
    config:
      discovery:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: card-service
          uri: lb://card-service
          predicates:
             - Path=/api/cards/**
        - id: service-service
          uri: lb://service-service
          predicates:
            - Path=/api/services/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

server:
  port: 8222
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

jwt:
  token:
    validity:
      864_000_000
  secret:
    30M18gaU4TRNnOPIcsOsp6BoCrvkxUZ2rej8OuQILnahRGarCku0eAjl5QPKpeI7gMdWSZ+9523gly72Efs4CQ==