spring:
  kafka:
    consumer:
      group-id: notification-group
    bootstrap-servers: localhost:9092
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: notification
  mail:
    port: 587
    host: smt.gmail.com
    username: siroj.abdumavlonov369@gmail.com
    password: "kpxu zawx ccwd zscr"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
