spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: service-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411
  kafka:
    bootstrap-servers: localhost:9092
logging:
  level:
    root: info
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true