spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: card-service
  zipkin:
    base-url: http://localhost:9411
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: card-group
  datasource:
    url: jdbc:postgresql://localhost:5433/card
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
